#!/bin/bash

# See LICENSE for license details.

# Helper script that launches GTKWave for a specific [vcd-file] using
# scripts/addWavesRecursive.tcl to populate the waveform window with
# signals grouped by module.

usage () {
    echo "Usage: $0 [vcd-file]" >&2
}

base_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/..
ENV=env PATH=$base_dir/opt/bin:$PATH

if [ $# -ne 1 ]; then
    usage
    exit
fi

if [ ! -f $base_dir/opt/bin/gtkwave ]; then
    make -C $base_dir gtkwave;
fi;

echo "[INFO] Preprocessing $1 to generate $1.gtkw" >&2
time $ENV gtkwave -g -S $base_dir/scripts/addWavesRecursive.tcl $1 > $1.gtkw
echo "[INFO] Launching graphical GTKWave..." >&2
$ENV gtkwave -g $1 $1.gtkw
